var name_generator = {
 	names: {
	 	0: ["Major","Captain","Senor","Doctor","Professor","Commodore","Baron","Generalissimo","Comandante","Madame","Chief","Maestro","Commander","Col.","Sargent","Mama","Sir","Admiral","Herr","Mademoiselle","Sultan","Dame","Master","President","Viceroy","Count","Lord","Frau","Sheik","Uncle","Auntie","Pop","Granny","Reverend","Guru","Monsignor","Cardinal","Senator","Brother","Sister","Field","Kapellmeister","Mother","Rapmaster","Brigadier","Inspector","Ensign","Prime","Saint","Grand","Judge","Alderman","Mayor","King","Emir","Prince","Ambassador","Secretary","Dean","Burgomaster","Squire","Superintendent","Special","Specialist","Rear","Chancellor","Headmaster","Governor","Representative","Citizen","Mr.","Mrs.","Skipper","Camp","Ringmaster","High","Deputy","Parson","Warden","Private","Deacon","Lance","Bishop","Chief","Lance","Kaiser","Emperor","Boss","Don","Godfather","Doc","Kid","Cheiftan","Director","Wine","Coach","Scoutmaster","Inspector","Royal","Emir"],
		1: ["Chumleigh's","Whizbang's","Bandersnaatch's","Ramshackle's","Bounder's","Flimflam's","Mountebank's","Whopper's","Balderdash's","Snarltooth's","Scamalot's","Trustworthy's","Goodhart's","Feelwell's","Hogwash's","Pondscum's","Adventure's","Wonderjoy's","Honeytounge's","Ballyhoo's","Friendly's","Wiseacre's","Chef","Wormtounge's","Wizard's","Harmony's","Bamboozle's","Slavetrade's","Houdeeny's","Whozit's","Tralfamador's","Fancypants's","Prankster's","Monacle's","Moustache's","Razzledazzle's","Dreamcatcher's","Murkwood's","Flabberghast's","Scofflaw's","Master","Dittybag's","Superior","Duplicity's","Crackpot's","Merriwweather's","Whipsnade's","Minister","Bobmbast's","Dragon","Jumble's","Doublecross's","Hilarity's","Delusional's","Purity's","Packrat's","Snapcrackle's","General","Gazoonteit's","Ticklebottom's","Gateway's","Curmudgeon's","Agent","First","Admiral","Gladhand's","Flashypant's","Magic's","Mystery's","Hollywood's","Iowa's","Reliable's","Snugglebug's","Director","Jabberwock's","Priestess","Hobnobble's","Teabag's","Socksoff's","Reality's","Perfecto's","Corporal","Cakehole's","Warrant","Corporal","Hooey's","Poppycock's","Genderbender's","Fiddlefaddle's","Horsefeathers'","Pomposity's","Horsethief's","Scalawag's","Beautiful's","Steward","Organic's","McShifty's","General","Mountie","Socksoff's"],
		2: ["Amazing","Distracting","Disturbing","Inciting","Exciting","Alarming","Merry","Impassive","Disdaining","Remaining","Complaining","Entertaining","Astounding","Confounding","Distorting","Amusing","Confusing","Enchanting","Rewarding","Entrancing","Awesome","Fantastic","Wanderlust's","Tremendous","Nostalgic","Stupendous","Pretentious","Notorious","Renowned","Remarkable","Original","Dramatic","Uncompromising","Delightful","Attractive","Charming","Pedantic","Bewitching","Fetching","Adequate","Fudpucker's","Darling","Bojangles'","Predictable","Uncanny","Fantabulous","Loverly","Snakeoil's","Glorious","Philanderer's","Notorious","Innocuous","Pretentious","Award","Sparkling","Fun-filled","Disquieting","Goldenrod's","Affecting","Prodigious","Ginormous","Colossal","Flapdoodle's","Class","Phonyface's","Inspiring","Jaw-dropping","Flamboyant","Colorful","Stirring","(your","Spellbinding","Captivating","Laffy's","Beguiling","Snickersnack's","Bewitching","Mind-blowing","Tremendous","Surreal","Ecstatic","Blabbermouth's","Unconventional","Officer","Bunkum's","Redoubtable","Impeccable","Awesome","Enthralling","Sanctimonious","Super-Cool","Deluxe","Genuine","Gargantuan","Magnanamous'","Magnificent","Naturalistic","Bottomdealer's","Parody's","Bewitching"],
		3: ["Traveling","Wandering","Itinerant","Touring","Ambling","Adventuring","Apprenticing","Relocating","Interloping","Navigating","Stationery","Time-traveling","Free Floating","Vacationing","Delaying","Nomadic","Temporary","Disappearing","Rambling","Freeloading","Panhandling","Improvising","Gigantic","Visiting","Scampering","Flitting","Overperforming","Popular","Fumigating","Pandering","Frolicking","Pontificating","Plummeting","Orbitting","Dancing","Stalking","Streaking","Partying","Sightseeing","Pandering","Disappointing","Scooting","Unique","Routed","Heavily","Revolving","Deserting","Fabulous","Ambling","Delicious","Criss-crossing","Gonzo","Cross-dressing","Winning","Fucking","Standard","Deluxe","Unrelenting","Island","Transcontinental","Impoverished","Tri-County","Phantasmagorical","Sleezebellie's","Impressive","Marauding","Guerila","Midnight","Fly-by-night","Colonizing","state)","Spreading","Rampaging","Explosive","Globetrotting","Enticing","Pulsating","Contagious","Nomadic","Intramural","Family","Bitchin'","Forthcoming","Showoff's","Fashionable","Sprawling","Available","Plummeting","Inspirational","Torrential","Old","Fleeting","Ephemeral","Brand","Super","Automatic","Instant","Groovy","Head-turning","Popular"],
		4: ["Circus","Carnival","Revue","Exposition","Museum","Pageant","Theatricality","Vaudeville","Variety","Display","Comedy","Cock Fight","Demonstration","Lecture Tour","Medicine Show","Revival Show","Burlesque","Mime Troupe","Library","Company","Freak Show","Talent Pool","Educating Cheerleaders","Drill Team","Orchestra","Mudshow","Passion Play","Puppet Show","Magic Show","Comedia Troupe","Minstrel Show","Trailer Park","Sideshow","Caravan","Festival","Fiesta","Lolapalooza","Music Hall","Monkey House","Event","Retreating Dance Party","Free-For-All","Motoring Salvation Hour","Rodeo","Scheduled Social Occasion","Fruit Stand","Emporium","Absconding Bazaar","Tent Show","Cavorting Pageant","Presentation","Exposition","Parade of Talent","Universal Project","Jamboree","Jubilee","Amusement","Formidable Production","Hopping Convoy","Express","Blow-Out","Divertissement","Moveable Rumpus","Epic Transportable Horde","Revolutionary Clan","Familia","Old West Show","Hippodrome","Dance Marathon","Escapades","Startling Epidemic Follies","Emporium","Allstars","Farflung Gymnastica","Compendium","Gyrating Parlour Tricks","Fun House","Amateur Hour","Saturnalia","Headliners","Style Bazaar","Ass Full Monty Stampede","Street Fair","Doggonest Employable Spectacle","Recurring Heydey","Masquerade","Mardis Gras","Band","Ironica","Demonstration","Fashioned Wonderland","Auditorium","Laserium","New Barnyard","Unprecedented Creative Zoo","Bizarrium","Mirthatorium","Twisted Inner Sanctum","Serial Oddities","Circus"],
		5: ["Combined","Inflamed","Remixed","Reduxed","Distilled","Assorted","Freerange","Interbred","Reclaimed","Detained","Insane","Inclined","Refined","Homogenized","Blended","Shaken","Collated","Collected","Conjoined","Related","Fractured","Distorted","Infused","Hybrid","Mutated","Preferred","Secluded","Exposed","Registered","Distinct","Discreet","Shuffled","Cataloged","Disjointed","Diffused","Jumbled","Congealed","Contiguous","Random","Aggregated","Liquidated","Cross-polinated","Pre-sorted","Pluralized","Intertwined","Multitudinous","Homogenized","Propinquitous","Synergistic","Interchangeable","Inevitable","Handpicked","Aggregate","Clamorous","Twin","Amalgamated","Conglomerated","Interspersed","Alternating","Mixed","Diversified","Osterized","Simultaneous","Committed","Obligatory","Recycled","Heaped","Dispersed","Modular","Symbiotic","Naturally","Total","Reassembled","Fibricated","Digitized","Melded","Compounded","Composite","Synthesized","Banded","Networked","Commingled","Thrown-togehter","Mish-moshed","Allied","Connected","Motley","Handstitched","Recruited","Volunteer","Marbelized","Episodic","Sporadic","Precipitated","Aroused","Rejected","Declined","Morphed","Compatible","Declined"],
		6: ["Pandemonium","Theatromania","Confusion","Chaos","Cacaphony","Anarchy","Ludicrous","Foolishness","Disorder","Surprise","Calamity","Mayhem","Infinity","Disaster","Whimsey","Wonderment","Hurly","Synchronicity","Polyphonium","Barbarism","Exuberance","Imagination","Panic","Nirvana","Decorum","Delerium","Holographic","Schizophrenia","Plentitude","Tomfoolery","Mob","Fantasy","Imaginarium","Amnesia","Apocalypse","Utopian","Wildness","Longevity","Netherworld","Trinity","Conundrum","Independence","Time-warp","Uproar","Agitation","Serendipity","Rapture","Destiny","Synchronization","Grace","Disruption","Existential","Calamity","Mirth","Hurly","Clusterfuck","Exploding","Uproar","Hellish","Heartstopping","Forbidden","Danger","Medieval","Psychedelia","Weirdsville","Asylum","Conundrum","Epiphany","Platitudinous","Breakthrough","Selected","Lunacy","Preposturous","Craziness","Dementia","Disturbance","Madness","Tomfoolery","Absurdity","Idiocy","Imbecility","Folly","Nonsense","Silliness","Zaniness","Commotion","Brouhaha","Wackiness","Nuttiness","Extreme","Turmoil","Merriment","Genius","Demolition","Eruption","Scandal","Outrage","Exasperation","Discord","Barbarism"],
		7: ["Shadow","Whisper","Mystery","Echo","Penumbra","Cloud","Wave","Afterglow","Memory","Silence","Ghost","Fragment","Murk","Image","Flicker","Silhouette","Burly","Message","Phantom","Dream","Fantasy","Flippery","Lightening","Radiation","Hypnosis","Light","Spirit","Tempest","Destiny","Stop-action","Mentality","Lyric","Rapture","Ragtime","Desire","Stencil","Ascension","Morphing","Pastiche","Misdirection","Grassroots","Air","Prayer","Mist","Eclipse","Ether","Rumor","Doppleganger","Vapor","Steampunk","Mystery","Virtual","Dewdrop","Web","Burly","Laser","Primordial","Reflection","Shimmer","Glow","Zone","Glimmer","Inkblot","Bubble","Wicker","Rebound","Reverb","Dustcloud","Feather","Screen","Insanity","Phantasm","Wraith","Spook","Haunt","Breath","Whiffle","Tracing","Ripple","Icicle","Stardust","Zephyr","Blossom","Wrinkle","Splash","Memory","Ruffle","Breeze","Lantern","Spinning","Stream","Fart","Gas","Prism","Pattern","Romance","Gust","Phantom","Overtone","Burly"],
		8: ["Show","Play","Skit","Cavalcade","Song","Pitch","Shtick","Routine","Feature","Version","Shindig","Happening","Fandango","Recital","Scene","Shuffle","Haiku Improvisation","Gala","Spectacle","Seance","Hootenanny","Staging","Escapade","Symposium","Ritual","Projection","Bigtime","Pow Wow","Convocation","Hoedown","Poetry Roundup","Celebration","Consortium","Ceremony","Encore","Barn Dance","Forum","Medley","Congregation","Runaround","Send-off","Ballet","Meeting","Revelry","Saturnalia","Fling","Bachanal","Town Hall","Revival","Sermon","Roleplay","Blitz","Reprise","Edition","Light Orgy","Hoop Dance","Coalition","Derby","Spree","Launch","Heat Camera Obscura","Specialty","Tableau","Peep Show","World","Quartet","Reunion","Whistle Stop","Forecast","Cabinet","Veil Mummery","Fandango","Bed-in","Pantomime","Presentation","Miraculum","Roundtable","Luau","Caper","Sketch","Promenade","Ball","Frolic","Cotllion","Concert","Incident","Musicale","Tale","Rhapsody","Serenade","Relapse","Jam","Flash","Club","Scrapbook","Popup","Illustration","Turn","Offering","Routine"]
	},

	generate_name: function() {
		var name = "";

		for (i = 0; i < 9; i++) {
			if (i == 5) name += "and ";
			name += this.names[i][Math.floor(Math.random() * this.names[i].length)] + " ";
		}

		$('#circus-name').html(name);
	}
};


$(function() {
	name_generator.generate_name();

	$('#generate').on('click', function(e) {
		e.preventDefault();
		name_generator.generate_name();
	});
});